import pyjokes
joke = pyjokes.get_joke()
name = input("Enter your name: ")
print(f"Hello, {name}! there is a joke for you:\n{joke}")
print("We will now give various cases of your name")
name_uppercase = name.upper()
name_lowercase = name.lower()
name_titlecase = name.title()
print(f"Uppercase: {name_uppercase}")
print(f"Lowercase: {name_lowercase}")
print(f"Title Case: {name_titlecase}")
jk = pyjokes.get_joke()
print(f"{name} once said, \"{jk}\"")
